name = "bookmark-demo"
main = "src/worker/index.ts"
compatibility_date = "2026-05-16"

[vars]
DEMO = "true"

[triggers]
crons = ["0 * * * *"]

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "bookmark-demo"
database_id = "0cda4a8c-a983-4573-b4af-88b9e5f244f1"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "OGP_BUCKET"
bucket_name = "bookmark-demo-ogp"
